### ISSUE TITLE
Homemanager using Docker container

### ISSUE THREAD

**Issue by zeduperes** [rpolenthon/homemanagerAppModeKit#1]
I have homebridge running on my Raspberry Pi 3+ using the Docker container: oznu/docker-homebridge
I would like to know how to set up the Homemanager App with the docker homebridge container.

**Comment by rpolenthon** [comment]
Currently Docker integration is not available through AppMode presets. We haven’t time yet to setup our own Docker and test which commands can be used, so if anyone can contribute which commands can be used with dockers, we can provide the official support soon. 

Generally every support can be done by every user on his own through the experimental mode and in combination with the HMAppModeKit. 


You can write me a mail to info@homemanager-app.de

**Comment by slipstream1** [comment]
hi - i see docker is in beta support
ive followed this https://www.reddit.com/r/homeassistant/comments/cit9jr/running_homebridge_in_hassio/
can i use homemanger to now manage it ? 

struggling to work out what i have to put in admin/password and instance paths

**Comment by rpolenthon** [comment]
@slipstream1 I will answer you in some minutes.

The issue gets closed because next details will be shared via email.
